security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        my_db_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
         main:
            anonymous: ~
            form_login:
                login_path: login
                default_target_path: admin
                check_path: login
            logout:
                path:   /logout
                target: /


    access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }